services:
  Mollie\Builder\FormBuilder:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\CountryService'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Service\ConfigFieldService'
      - '@Mollie\Service\MolCarrierInformationService'
      - '@language'
      - '@smarty'
      - '@link'
      - '@Mollie\Provider\CreditCardLogoProvider'

  Mollie\Builder\ApiTestFeedbackBuilder:
    arguments:
      - '@=service("mollie.factory.module_factory").getModuleVersion()'
      - '@Mollie\Service\ApiService'
