services:
  _defaults:
    public: true

  Mollie\Builder\FormBuilder:
    class: Mollie\Builder\FormBuilder
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\CountryService'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Service\ConfigFieldService'
      - '@Mollie\Service\MolCarrierInformationService'
      - '@mollie.language'
      - '@mollie.smarty'
      - '@mollie.link'
      - '@Mollie\Provider\CreditCardLogoProvider'

  Mollie\Builder\ApiTestFeedbackBuilder:
    class: Mollie\Builder\ApiTestFeedbackBuilder
    arguments:
      - '@=service("mollie.factory.module_factory").getModuleVersion()'
      - '@Mollie\Service\ApiKeyService'

  Mollie\Builder\InvoicePdfTemplateBuilder:
    class: Mollie\Builder\InvoicePdfTemplateBuilder
    arguments:
      - '@Mollie\Repository\OrderFeeRepository'

  Mollie\Builder\Content\BaseInfoBlock:
    class: Mollie\Builder\Content\BaseInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\RoundingModeInfoBlock:
    class: Mollie\Builder\Content\RoundingModeInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\LogoInfoBlock:
    class: Mollie\Builder\Content\LogoInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\UpdateMessageInfoBlock:
    class: Mollie\Builder\Content\UpdateMessageInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\UpgradeNoticeService'
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Provider\UpdateMessageProvider'

  Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock:
    class: Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\IssuerService'

  Mollie\Builder\ApplePayDirect\ApplePayOrderBuilder:
    class: Mollie\Builder\ApplePayDirect\ApplePayOrderBuilder

  Mollie\Builder\ApplePayDirect\ApplePayCarriersBuilder:
    class: Mollie\Builder\ApplePayDirect\ApplePayCarriersBuilder

  Mollie\Builder\ApplePayDirect\ApplePayProductBuilder:
    class: Mollie\Builder\ApplePayDirect\ApplePayProductBuilder
