services:
  Mollie\Handler\Certificate\CertificateHandlerInterface: '@Mollie\Handler\Certificate\ApplePayDirectCertificateHandler'

  Mollie\Handler\Certificate\ApplePayDirectCertificateHandler:
    class: Mollie\Handler\Certificate\ApplePayDirectCertificateHandler
    arguments:
      - '@mollie'
