imports:
  - { resource: builder.yml }
  - { resource: service.yml }
  - { resource: repository.yml }
  - { resource: context.yml }
  - { resource: factory.yml }
  - { resource: presenter.yml }
  - { resource: validator.yml }
  - { resource: command.yml }
  - { resource: provider.yml }

services:
  mollie:
    class: 'Mollie'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mollie'

  Mollie\Install\Installer:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ImageService'

  Mollie\Install\Uninstall:
    arguments:
      - '@mollie'
