services:
  mollie.context:
    class: 'Context'
    factory: ['Mollie\Factory\ContextFactory', 'getContext']

  mollie.controller:
    class: 'Controller'
    factory: ['Mollie\Factory\ContextFactory', 'getController']

  mollie.cookie:
    class: 'Cookie'
    factory: ['Mollie\Factory\ContextFactory', 'getCookie']

  mollie.language:
    class: 'Language'
    factory: ['Mollie\Factory\ContextFactory', 'getLanguage']

  mollie.currency:
    class: 'Currency'
    factory: ['Mollie\Factory\ContextFactory', 'getCurrency']

  mollie.smarty:
    class: 'Smarty'
    factory: ['Mollie\Factory\ContextFactory', 'getSmarty']

  mollie.shop:
    class: 'Shop'
    factory: ['Mollie\Factory\ContextFactory', 'getShop']

  mollie.link:
    class: 'Shop'
    factory: ['Mollie\Factory\ContextFactory', 'getLink']

  mollie.country:
    class: 'Shop'
    factory: ['Mollie\Factory\ContextFactory', 'getCountry']
