services:
  Mollie\Handler\Settings\PaymentMethodPositionHandler:
    class: Mollie\Handler\Settings\PaymentMethodPositionHandler
    arguments:
      - '@Mollie\Repository\PaymentMethodRepositoryInterface'

  Mollie\Handler\Settings\PaymentMethodPositionHandlerInterface: '@Mollie\Handler\Settings\PaymentMethodPositionHandler'

  Mollie\Handler\Exception\OrderExceptionHandler:
    class: Mollie\Handler\Exception\OrderExceptionHandler

  Mollie\Handler\Api\OrderEndpointPaymentTypeHandler:
    class: Mollie\Handler\Api\OrderEndpointPaymentTypeHandler
    arguments:
      - '@Mollie\Verification\PaymentType\CanBeRegularPaymentType'

  Mollie\Handler\Shipment\ShipmentSenderHandler:
    class: Mollie\Handler\Shipment\ShipmentSenderHandler
    arguments:
      - '@Mollie\Verification\Shipment\CanSendShipment'
      - '@Mollie\Service\Shipment\ShipmentInformationSender'
      - '@Mollie\Service\ExceptionService'
      - '@Mollie\Logger\PrestaLogger'

  Mollie\Handler\Shipment\ShipmentSenderHandlerInterface: '@Mollie\Handler\Shipment\ShipmentSenderHandler'

  Mollie\Handler\PaymentOption\PaymentOptionHandler:
    class: Mollie\Handler\PaymentOption\PaymentOptionHandler
    arguments:
      - '@Mollie\Provider\PaymentOption\BasePaymentOptionProvider'
      - '@Mollie\Provider\PaymentOption\CreditCardPaymentOptionProvider'
      - '@Mollie\Provider\PaymentOption\CreditCardSingleClickPaymentOptionProvider'
      - '@Mollie\Provider\PaymentOption\IdealPaymentOptionProvider'
      - '@Mollie\Repository\MolCustomerRepository'
      - '@mollie.customer'

  Mollie\Handler\PaymentOption\PaymentOptionHandlerInterface: '@Mollie\Handler\PaymentOption\PaymentOptionHandler'

  Mollie\Handler\ErrorHandler\ErrorHandler:
    class: Mollie\Handler\ErrorHandler\ErrorHandler
    arguments:
      - '@mollie'

  Mollie\Handler\Order\OrderCreationHandler:
    class: Mollie\Handler\Order\OrderCreationHandler
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Handler\Order\OrderFeeHandler'
      - '@Mollie\Service\OrderStatusService'

  Mollie\Handler\Order\OrderFeeHandler:
    class: Mollie\Handler\Order\OrderFeeHandler
    arguments:
      - '@Mollie\Service\OrderFeeService'
      - '@Mollie\Service\PaymentMethodService'

  Mollie\Handler\RetryHandlerInterface: '@Mollie\Handler\RetryHandler'

  Mollie\Handler\RetryHandler:
    class: Mollie\Handler\RetryHandler
