services:
  Mollie\Provider\CreditCardLogoProvider:
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'

  Mollie\Service\PaymentMethod\PaymentMethodSortProvider:

  Mollie\Provider\PhoneNumberProvider:
    arguments:
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Logger\PrestaLogger'
