services:
  _defaults:
    public: true

  Mollie\Provider\CreditCardLogoProvider:
    class: Mollie\Provider\CreditCardLogoProvider
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'

  Mollie\Service\PaymentMethod\PaymentMethodSortProvider:
    class: Mollie\Service\PaymentMethod\PaymentMethodSortProvider

  Mollie\Provider\PhoneNumberProvider:
    class: Mollie\Provider\PhoneNumberProvider

  Mollie\Provider\Shipment\AutomaticShipmentSenderStatusesProvider:
    class: Mollie\Provider\Shipment\AutomaticShipmentSenderStatusesProvider
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Utility\Decoder\JsonDecoder'

  Mollie\Provider\PaymentType\RegularPaymentTypeIdentification:
    class: Mollie\Provider\PaymentType\RegularPaymentTypeIdentification

  Mollie\Provider\UpdateMessageProvider:
    class: Mollie\Provider\UpdateMessageProvider
    arguments:
      - '@mollie'

  Mollie\Provider\EnvironmentVersionProvider:
    class: Mollie\Provider\EnvironmentVersionProvider

  Mollie\Provider\StreetAndNumberProvider:
    class: Mollie\Provider\StreetAndNumberProvider

  Mollie\Provider\ProfileIdProviderInterface: '@Mollie\Provider\ProfileIdProvider'

  Mollie\Provider\ProfileIdProvider:
    class: Mollie\Provider\ProfileIdProvider
