services:
  _defaults:
    public: true

#  @deprecated - dont call repositories directly, use interface instead
  Mollie\Repository\PaymentMethodRepository:
    class: Mollie\Repository\PaymentMethodRepository

  Mollie\Repository\PaymentMethodRepositoryInterface: '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Repository\OrderFeeRepository:
    class: Mollie\Repository\OrderFeeRepository

  Mollie\Repository\CountryRepository:
    class: Mollie\Repository\CountryRepository

  Mollie\Repository\OrderShipmentRepository:
    class: Mollie\Repository\OrderShipmentRepository

  Mollie\Repository\MethodCountryRepository:
    class: Mollie\Repository\MethodCountryRepository

  Mollie\Repository\MolCarrierInformationRepository:
    class: Mollie\Repository\MolCarrierInformationRepository

  Mollie\Repository\ModuleRepository:
    class: Mollie\Repository\ModuleRepository

  Mollie\Repository\PendingOrderCartRepository:
    class: Mollie\Repository\PendingOrderCartRepository
    arguments:
      - 'MolPendingOrderCart'

  Mollie\Repository\MolCustomerRepository:
    class: Mollie\Repository\MolCustomerRepository
    arguments:
      - 'MolCustomer'

  Mollie\Repository\AttributeRepository:
    class: Mollie\Repository\AttributeRepository

  Mollie\Repository\OrderStateRepository:
    class: Mollie\Repository\OrderStateRepository

  Mollie\Repository\OrderRepository:
    class: Mollie\Repository\OrderRepository

  Mollie\Repository\OrderCartRuleRepository:
    class: Mollie\Repository\OrderCartRuleRepository

  Mollie\Repository\CartRuleRepository:
    class: Mollie\Repository\CartRuleRepository

  Mollie\Repository\PendingOrderCartRuleRepository:
    class: Mollie\Repository\PendingOrderCartRuleRepository

  Mollie\Repository\CurrencyRepository:
    class: Mollie\Repository\CurrencyRepository

  Mollie\Repository\CurrencyRepositoryInterface: '@Mollie\Repository\CurrencyRepository'
