services:
  Mollie\Service\OrderFeeService:

  Mollie\Service\PaymentMethodService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\MethodCountryRepository'
      - '@Mollie\Service\CartLinesService'

  Mollie\Service\ApiService:
    arguments:
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\ConfigFieldService:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\UrlPathService:
    arguments:
      - '@mollie'

  Mollie\Service\IssuerService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\RefundService:
    arguments:
      - '@mollie'

  Mollie\Service\ShipService:
    arguments:
      - '@mollie'

  Mollie\Service\CancelService:
    arguments:
      - '@mollie'

  Mollie\Service\CarrierService:

  Mollie\Service\OrderStatusService:

  Mollie\Service\ErrorDisplayService:

  Mollie\Service\CountryService:
    arguments:
      - '@mollie'

  Mollie\Service\SettingsSaveService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\MolCarrierInformationService'

  Mollie\Service\ShipmentService:
    arguments:
      - '@Mollie\Repository\OrderShipmentRepository'
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\CartLinesService:
    arguments:
      - '@mollie'

  Mollie\Service\MollieOrderInfoService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\RefundService'
      - '@Mollie\Service\ShipService'
      - '@Mollie\Service\CancelService'
      - '@Mollie\Service\ShipmentService'
      - '@Mollie\Service\ApiService'

  Mollie\Service\MolCarrierInformationService:
    arguments:
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\LanguageService:
    arguments:
      - '@mollie'

  Mollie\Service\CartDuplicationService:

  Mollie\Service\OrderCartAssociationService:
    arguments:
      - '@Mollie\Service\CartDuplicationService'

  Mollie\Service\RejectPendingOrderService:
    arguments:
      - '@Mollie\Repository\PendingOrderCartRepository'

  Mollie\Service\MemorizeCartService:
    arguments:
      - '@Mollie\Service\RejectPendingOrderService'
      - '@Mollie\Service\OrderCartAssociationService'