services:
  Mollie\Service\OrderFeeService:
    class: Mollie\Service\OrderFeeService

  Mollie\Service\PaymentMethodService:
    class: Mollie\Service\PaymentMethodService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\MethodCountryRepository'
      - '@Mollie\Service\CartLinesService'
      - '@Mollie\Service\PaymentsTranslationService'
      - '@Mollie\Service\CustomerService'
      - '@Mollie\Provider\CreditCardLogoProvider'
      - '@Mollie\Service\PaymentMethod\PaymentMethodSortProvider'
      - '@Mollie\Provider\PhoneNumberProvider'
      - '@Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation'
      - '@mollie.country'
      - '@mollie.shop'

  Mollie\Service\ApiService:
    class: Mollie\Service\ApiService
    arguments:
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Service\PaymentMethod\PaymentMethodSortProvider'
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\ConfigFieldService:
    class: Mollie\Service\ConfigFieldService
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\IssuerService:
    class: Mollie\Service\IssuerService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\RefundService:
    class: Mollie\Service\RefundService
    arguments:
      - '@mollie'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\ShipService:
    class: Mollie\Service\ShipService
    arguments:
      - '@mollie'

  Mollie\Service\CancelService:
    class: Mollie\Service\CancelService
    arguments:
      - '@mollie'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\CarrierService:
    class: Mollie\Service\CarrierService

  Mollie\Service\OrderStatusService:
    class: Mollie\Service\OrderStatusService
    arguments:
      - '@Mollie\Service\MailService'

  Mollie\Service\ErrorDisplayService:
    class: Mollie\Service\ErrorDisplayService

  Mollie\Service\OrderStateImageService:
    class: Mollie\Service\OrderStateImageService

  Mollie\Service\CountryService:
    class: Mollie\Service\CountryService
    arguments:
      - '@mollie'

  Mollie\Service\SettingsSaveService:
    class: Mollie\Service\SettingsSaveService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\MolCarrierInformationService'
      - '@Mollie\Handler\Settings\PaymentMethodPositionHandlerInterface'
      - '@Mollie\Service\ApiKeyService'

  Mollie\Service\ShipmentService:
    class: Mollie\Service\ShipmentService
    arguments:
      - '@Mollie\Repository\OrderShipmentRepository'
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\CartLinesService:
    class: Mollie\Service\CartLinesService
    arguments:
      - '@Mollie\Service\LanguageService'
      - '@Mollie\Service\VoucherService'
      - '@Mollie\Adapter\ToolsAdapter'

  Mollie\Service\CustomerService:
    class: Mollie\Service\CustomerService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\MolCustomerRepository'

  Mollie\Service\MollieOrderInfoService:
    class: Mollie\Service\MollieOrderInfoService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepositoryInterface'
      - '@Mollie\Service\RefundService'
      - '@Mollie\Service\ShipService'
      - '@Mollie\Service\CancelService'
      - '@Mollie\Service\ShipmentService'
      - '@Mollie\Service\ApiService'

  Mollie\Service\MolCarrierInformationService:
    class: Mollie\Service\MolCarrierInformationService
    arguments:
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\LanguageService:
    class: Mollie\Service\LanguageService
    arguments:
      - '@mollie'

  Mollie\Service\CartDuplicationService:
    class: Mollie\Service\CartDuplicationService
    arguments:
      - '@Mollie\Service\CartRuleDuplicationService'
      - '@Mollie\Handler\CartRule\CartRuleQuantityResetHandler'

  Mollie\Service\CartRuleDuplicationService:
    class: Mollie\Service\CartRuleDuplicationService
    arguments:
      - '@Mollie\Repository\CartRuleRepository'

  Mollie\Service\OrderCartAssociationService:
    class: Mollie\Service\OrderCartAssociationService
    arguments:
      - '@Mollie\Service\CartDuplicationService'

  Mollie\Service\MemorizeCartService:
    class: Mollie\Service\MemorizeCartService
    arguments:
      - '@Mollie\Service\OrderCartAssociationService'
      - '@Mollie\Repository\PendingOrderCartRepository'

  Mollie\Service\RepeatOrderLinkFactory:
    class: Mollie\Service\RepeatOrderLinkFactory

  Mollie\Logger\PrestaLogger:
    class: Mollie\Logger\PrestaLogger

  Psr\Log\LoggerInterface: '@Mollie\Logger\PrestaLogger'

  Mollie\Service\RestorePendingCartService:
    class: Mollie\Service\RestorePendingCartService
    arguments:
      - '@Mollie\Repository\PendingOrderCartRepository'

  Mollie\Service\TransactionService:
    class: Mollie\Service\TransactionService
    arguments:
      - '@mollie'
      - '@Mollie\Service\OrderStatusService'
      - '@Mollie\Service\OrderFeeService'

  Mollie\Service\MolliePaymentMailService:
    class: Mollie\Service\MolliePaymentMailService
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\MailService'

  Mollie\Service\MailService:
    class: Mollie\Service\MailService
    arguments:
      - '@mollie'

  Mollie\Service\PaymentsTranslationService:
    class: Mollie\Service\PaymentsTranslationService
    arguments:
      - '@mollie'
      - '@Mollie\Service\LanguageService'

  Mollie\Service\PaymentReturnService:
    class: Mollie\Service\PaymentReturnService
    arguments:
      - '@mollie'
      - '@Mollie\Service\CartDuplicationService'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\RepeatOrderLinkFactory'
      - '@Mollie\Service\TransactionService'
      - '@Mollie\Handler\CartRule\CartRuleQuantityChangeHandler'

  Mollie\Service\UpgradeNoticeService:
    class: Mollie\Service\UpgradeNoticeService

  Mollie\Service\VoucherService:
    class: Mollie\Service\VoucherService
    arguments:
      - '@Mollie\Repository\AttributeRepository'
      - '@Mollie\Adapter\ConfigurationAdapter'

  Mollie\Service\ExceptionService:
    class: Mollie\Service\ExceptionService
    arguments:
      - '@mollie'

  Mollie\Service\ApiKeyService:
    class: Mollie\Service\ApiKeyService

  Mollie\Handler\CartRule\CartRuleQuantityChangeHandler:
    class: Mollie\Handler\CartRule\CartRuleQuantityChangeHandler
    arguments:
      - '@Mollie\Repository\PendingOrderCartRuleRepository'
      - '@Mollie\Repository\OrderCartRuleRepository'
      - '@Mollie\Repository\CartRuleRepository'
      - '@Mollie\Repository\OrderRepository'

  Mollie\Handler\CartRule\CartRuleQuantityResetHandler:
    class: Mollie\Handler\CartRule\CartRuleQuantityResetHandler
    arguments:
      - '@Mollie\Repository\PendingOrderCartRuleRepository'
      - '@Mollie\Repository\OrderCartRuleRepository'
      - '@Mollie\Repository\CartRuleRepository'
      - '@Mollie\Repository\OrderRepository'

  Mollie\Service\Shipment\ShipmentInformationSender:
    class: Mollie\Service\Shipment\ShipmentInformationSender
    arguments:
      - '@Mollie\Repository\PaymentMethodRepositoryInterface'
      - '@Mollie\Service\ShipmentService'

  Mollie\Service\Shipment\ShipmentInformationSenderInterface: '@Mollie\Service\Shipment\ShipmentInformationSender'

  Mollie\Service\Content\SmartyTemplateParser:
    class: Mollie\Service\Content\SmartyTemplateParser

  Mollie\Service\Content\TemplateParserInterface: '@Mollie\Service\Content\SmartyTemplateParser'

  Mollie\Service\EntityManager\ObjectModelManager:
    class: Mollie\Service\EntityManager\ObjectModelManager
